# Generated by Django 3.2.12 on 2022-02-15 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='prefered_time',
            new_name='preferred_time',
        ),
    ]
