# Generated by Django 3.2.12 on 2022-02-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_prefered_time_contact_preferred_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='marked_for_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='send_to_csv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='send_to_salesforce',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='sent_to_csv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='sent_to_salesforce',
            field=models.BooleanField(default=False),
        ),
    ]
