# Generated by Django 3.2.12 on 2022-02-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_testimonials_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
