# Generated by Django 3.2.12 on 2022-02-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0003_testimonials_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('current_organization', models.TextField(max_length=200)),
                ('income_less_than_fifty_lakhs', models.BooleanField(default=False)),
                ('salary_income', models.IntegerField()),
                ('rental_income', models.IntegerField()),
                ('interest_income', models.IntegerField()),
                ('capital_gains', models.IntegerField()),
                ('other_income', models.IntegerField()),
                ('email_id', models.TextField(max_length=200)),
                ('contact_no', models.TextField(max_length=12)),
                ('marked_for_delete', models.BooleanField(default=False)),
                ('send_to_salesforce', models.BooleanField(default=False)),
                ('sent_to_salesforce', models.BooleanField(default=False)),
                ('send_to_csv', models.BooleanField(default=False)),
                ('sent_to_csv', models.BooleanField(default=False)),
            ],
        ),
    ]
