# Generated by Django 3.2.12 on 2022-02-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0005_auto_20220214_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('company_address', models.CharField(max_length=200)),
                ('company_logo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
